GET http://localhost:8800/barang


###
POST http://localhost:8800/barang
Content-Type: application/json

{
"nama" : "Taro", 
"kodeBarang" : "A0001", 
"jenisBarang" : "Makanan", 
"satuan" : "pcs",
"hargaBeli" : 9000,
"hargaJual" : 10000,
"idSupplier" : 1
}

###
PUT http://localhost:8800/barang/1
Content-Type: application/json

{
"nama" : "Sponge"
}


###
DELETE http://localhost:8800/barang/1
