GET http://localhost:8800/transPenjualanJoin


###
GET http://localhost:8800/barang

###
POST http://localhost:8800/barang
Content-Type: application/json

{
"nama" : "Taro", 
"kodeBarang" : "A0001", 
"jenisBarang" : "Makanan", 
"satuan" : "pcs",
"hargaBeli" : 9000,
"hargaJual" : 10000,
"supplierId" : 1
}

###
PUT http://localhost:8800/barang/1
Content-Type: application/json

{
"jumlah" : "10"
}


###
DELETE http://localhost:8800/barang/1
