const ActionType = {
    SET_NAMA_BARANG_PENJUALAN: 'SET_NAMA_BARANG_PENJUALAN',
    SET_KODE_BARANG_PENJUALAN: 'SET_KODE_BARANG_PENJUALAN',
    SET_JUMLAH_PENJUALAN: 'SET_JUMLAH_PENJUALAN',
    SET_JENIS_PENJUALAN: 'SET_JENIS_PENJUALAN',
    SET_HARGA_PENJUALAN: 'SET_HARGA_PENJUALAN',
    SET_ANGGOTA_PENJUALAN: 'SET_ANGGOTA_PENJUALAN',
    SET_TYPE_BAYAR_PENJUALAN: 'SET_TYPE_BAYAR_PENJUALAN',
    SET_FAKTUR_PENJUALAN: 'SET_FAKTUR_PENJUALAN'
}

export default ActionType