const ActionType = {
  // Penjualan
  SET_NAMA_BARANG_PENJUALAN: "SET_NAMA_BARANG_PENJUALAN",
  SET_KODE_BARANG_PENJUALAN: "SET_KODE_BARANG_PENJUALAN",
  SET_JUMLAH_PENJUALAN: "SET_JUMLAH_PENJUALAN",
  SET_JENIS_PENJUALAN: "SET_JENIS_PENJUALAN",
  SET_HARGA_PENJUALAN: "SET_HARGA_PENJUALAN",
  SET_ANGGOTA_PENJUALAN: "SET_ANGGOTA_PENJUALAN",
  SET_TYPE_BAYAR_PENJUALAN: "SET_TYPE_BAYAR_PENJUALAN",
  SET_FAKTUR_PENJUALAN: "SET_FAKTUR_PENJUALAN",
  SET_ID_SUPPLIER_PENJUALAN: "SET_ID_SUPPLIER_PENJUALAN",

  // Pembelian
  SET_NAMA_BARANG_PEMBELIAN: "SET_NAMA_BARANG_PEMBELIAN",
  SET_KODE_BARANG_PEMBELIAN: "SET_KODE_BARANG_PEMBELIAN",
  SET_JUMLAH_PEMBELIAN: "SET_JUMLAH_PEMBELIAN",
  SET_JENIS_PEMBELIAN: "SET_JENIS_PEMBELIAN",
  SET_SATUAN_PEMBELIAN: "SET_SATUAN_PEMBELIAN",
  SET_HARGA_PEMBELIAN: "SET_HARGA_PEMBELIAN",
  SET_HARGA_JUAL_PEMBELIAN: "SET_HARGA_JUAL_PEMBELIAN",
  SET_SUPPLIER_PEMBELIAN: "SET_SUPPLIER_PEMBELIAN",
  SET_FAKTUR_PEMBELIAN: "SET_FAKTUR_PEMBELIAN",
  SET_BARANG_ID: "SET_BARANG_ID",

  // Cicilan
  SET_ID_CICILAN: "SET_ID_CICILAN",
};

export default ActionType;
